point_cloud_topic:  /camera/depth/points
map_frame_id: "odom"
robot_base_frame_id: base_footprint
sensor_frame_id: camera_depth_optical_frame
robot_pose_with_covariance_topic: /base_footprint_pose
#robot_pose_with_covariance_topic: "/legodom/base_pose"
robot_pose_cache_size: 200
## the elevation map is moved along with the robot following a track point. This is the id of the tf frame in which the track point is defined.
#track_point_frame_id: "base_link"
track_point_frame_id: "odom"
## the elevation map is moved along with the robot following a track point. This is the position of the track point in the track_point_frame_id;
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
time_tolerance: 0.5
min_update_rate: 1;
fused_map_publishing_rate: 2
visibility_cleanup_rate: 2.5
enable_visibility_cleanup: false;
enable_continuous_cleanup: false;
## sensor processor
sensor_processor/apply_voxelgrid_filter: false;
sensor_processor/voxelgrid_filter_size: 0.025;

## elevation_map
length_in_x: 6.0
length_in_y: 6.0
position_x: 0.0
position_y: 0.0
resolution: 0.02
min_variance: 0.000009
max_variance: 0.01
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
